"""
Utilities package initialization.
"""

# Import from constants
from app.utils.constants import (
    ALLOWED_EXTENSIONS,
    CACHE_DAY,
    CACHE_LONG,
    CACHE_MEDIUM,
    CACHE_SHORT,
    CURRENCY_SYMBOLS,
    DATE_FORMATS,
    DEFAULT_CATEGORIES,
    DEFAULT_PAGE_SIZE,
    DESCRIPTION_MAX_LENGTH,
    EMAIL_MAX_LENGTH,
    HTTP_STATUS,
    MAX_FILE_SIZE,
    MAX_PAGE_SIZE,
    NOTES_MAX_LENGTH,
    PASSWORD_MIN_LENGTH,
    USERNAME_MAX_LENGTH,
    USERNAME_MIN_LENGTH,
    AccountStatus,
    BudgetPeriod,
    CategoryType,
    DateRange,
    ExportFormat,
    TransactionType,
    UserRoles,
)

# Import from decorators
from app.utils.decorators import (
    admin_required,
    cache_control,
    deprecated,
    fresh_jwt_required,
    handle_errors,
    paginate,
    rate_limit,
    retry,
    timing,
    validate_request,
)

# Import from helpers
from app.utils.helpers import (
    chunks,
    deep_get,
    dict_to_camel_case,
    dict_to_snake_case,
    extract_domain,
    format_currency,
    format_date,
    generate_token,
    generate_uuid,
    get_date_range,
    group_by,
    hash_string,
    paginate_query,
    parse_date,
    safe_divide,
    sanitize_html,
    truncate_string,
    validate_email,
)

# Import from validators
from app.utils.validators import (
    validate_amount,
    validate_date_format,
    validate_date_range,
    validate_email_format,
    validate_enum_value,
    validate_file_extension,
    validate_hex_color,
    validate_id,
    validate_json_schema,
    validate_numeric_range,
    validate_password_strength,
    validate_phone_number,
    validate_required,
    validate_string_length,
    validate_username,
    validate_uuid,
)

# Define what should be available when using "from app.utils import *"
__all__ = [
    # Constants
    "HTTP_STATUS",
    "TransactionType",
    "CategoryType",
    "BudgetPeriod",
    "UserRoles",
    "AccountStatus",
    "ExportFormat",
    "DateRange",
    "DEFAULT_CATEGORIES",
    "PASSWORD_MIN_LENGTH",
    "USERNAME_MIN_LENGTH",
    "USERNAME_MAX_LENGTH",
    "EMAIL_MAX_LENGTH",
    "DESCRIPTION_MAX_LENGTH",
    "NOTES_MAX_LENGTH",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "CACHE_SHORT",
    "CACHE_MEDIUM",
    "CACHE_LONG",
    "CACHE_DAY",
    "MAX_FILE_SIZE",
    "ALLOWED_EXTENSIONS",
    "DATE_FORMATS",
    "CURRENCY_SYMBOLS",
    # Decorators
    "validate_request",
    "paginate",
    "timing",
    "cache_control",
    "rate_limit",
    "handle_errors",
    "admin_required",
    "fresh_jwt_required",
    "deprecated",
    "retry",
    # Helpers
    "generate_uuid",
    "generate_token",
    "validate_email",
    "format_currency",
    "parse_date",
    "format_date",
    "get_date_range",
    "paginate_query",
    "dict_to_camel_case",
    "dict_to_snake_case",
    "safe_divide",
    "truncate_string",
    "hash_string",
    "sanitize_html",
    "extract_domain",
    "group_by",
    "chunks",
    "deep_get",
    # Validators
    "validate_required",
    "validate_string_length",
    "validate_numeric_range",
    "validate_email_format",
    "validate_date_format",
    "validate_enum_value",
    "validate_uuid",
    "validate_hex_color",
    "validate_phone_number",
    "validate_password_strength",
    "validate_username",
    "validate_file_extension",
    "validate_json_schema",
    "validate_amount",
    "validate_date_range",
    "validate_id",
]
