"""
Schemas package initialization.
"""

from app.schemas.analytics_schema import (
    AnalyticsFilterSchema,
    AnomalySchema,
    CashFlowSchema,
    CategoryBreakdownItemSchema,
    CategoryBreakdownSchema,
    ConfidenceSchema,
    DashboardSummarySchema,
    ForecastPeriodSchema,
    ForecastSchema,
    InsightSchema,
    KPISchema,
    MonthlyStatsSchema,
    NetWorthSchema,
    ProjectionSchema,
    TimeSeriesSchema,
    TrendSchema,
)
from app.schemas.budget_schema import (
    BudgetCreateSchema,
    BudgetFilterSchema,
    BudgetProgressSchema,
    BudgetSchema,
    BudgetStatusOverviewSchema,
    BudgetStatusSchema,
    BudgetSuggestionSchema,
    BudgetUpdateSchema,
)
from app.schemas.category_schema import (
    CategoryCreateSchema,
    CategoryFilterSchema,
    CategoryHierarchySchema,
    CategorySchema,
    CategoryStatsSchema,
    CategoryUpdateSchema,
)
from app.schemas.transaction_schema import (
    BulkTransactionSchema,
    RecurringTransactionSchema,
    TransactionCreateSchema,
    TransactionFilterSchema,
    TransactionImportSchema,
    TransactionSchema,
    TransactionSummarySchema,
    TransactionUpdateSchema,
)
from app.schemas.user_schema import (
    EmailVerificationSchema,
    PasswordChangeSchema,
    PasswordResetConfirmSchema,
    PasswordResetSchema,
    TokenResponseSchema,
    UserCreateSchema,
    UserLoginSchema,
    UserSchema,
    UserUpdateSchema,
)

__all__ = [
    # User schemas
    "UserSchema",
    "UserCreateSchema",
    "UserUpdateSchema",
    "UserLoginSchema",
    "PasswordChangeSchema",
    "PasswordResetSchema",
    "PasswordResetConfirmSchema",
    "EmailVerificationSchema",
    "TokenResponseSchema",
    # Category schemas
    "CategorySchema",
    "CategoryCreateSchema",
    "CategoryUpdateSchema",
    "CategoryFilterSchema",
    "CategoryHierarchySchema",
    "CategoryStatsSchema",
    # Transaction schemas
    "TransactionSchema",
    "TransactionCreateSchema",
    "TransactionUpdateSchema",
    "TransactionFilterSchema",
    "BulkTransactionSchema",
    "TransactionImportSchema",
    "TransactionSummarySchema",
    "RecurringTransactionSchema",
    # Analytics schemas
    "TimeSeriesSchema",
    "CategoryBreakdownSchema",
    "CategoryBreakdownItemSchema",
    "DashboardSummarySchema",
    "KPISchema",
    "TrendSchema",
    "MonthlyStatsSchema",
    "AnalyticsFilterSchema",
    "ForecastSchema",
    "ForecastPeriodSchema",
    "ConfidenceSchema",
    "InsightSchema",
    "AnomalySchema",
    "CashFlowSchema",
    "NetWorthSchema",
    "ProjectionSchema",
    # Budget schemas
    "BudgetSchema",
    "BudgetCreateSchema",
    "BudgetUpdateSchema",
    "BudgetFilterSchema",
    "BudgetStatusSchema",
    "BudgetStatusOverviewSchema",
    "BudgetSuggestionSchema",
    "BudgetProgressSchema",
]
